import {
  Baby,
  Banknote,
  BookOpen,
  Bus,
  Car,
  CircleEllipsis,
  Clapperboard,
  Coffee,
  Dog,
  Dumbbell,
  Fuel,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  Music,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Utensils,
  Wifi,
  Zap,
  type LucideIcon,
} from 'lucide-react'

// Category icons are stored by name. Only these are offered, so the full
// lucide set never ends up in the bundle. Step 10's category editor uses this list.

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: Utensils,
  coffee: Coffee,
  'shopping-cart': ShoppingCart,
  car: Car,
  bus: Bus,
  fuel: Fuel,
  plane: Plane,
  'shopping-bag': ShoppingBag,
  shirt: Shirt,
  clapperboard: Clapperboard,
  music: Music,
  receipt: Receipt,
  house: House,
  zap: Zap,
  wifi: Wifi,
  smartphone: Smartphone,
  repeat: Repeat,
  'heart-pulse': HeartPulse,
  dumbbell: Dumbbell,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  gift: Gift,
  baby: Baby,
  dog: Dog,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  'circle-ellipsis': CircleEllipsis,
}
